
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "12500:12500"

  frontend:
    build:
      context: .   
      dockerfile: Dockerfile
    ports:
      - "12000:80"
    depends_on:
      - backend